FROM debian:buster-slim

RUN apt-get update -y && apt-get install -y curl socat
# Taking last available version, see if issue when version mismatch with engine
# https://hasura.io/docs/latest/graphql/core/hasura-cli/install-hasura-cli/
RUN curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | INSTALL_PATH=/root/bin bash

WORKDIR /usr/src/hasura

COPY . .

CMD "./start.sh"
