query GetUsersAndAccountByEmail($email: String!) {
  users(where: { email: { _eq: $email } }) {
    accounts {
      ...AccountFields
    }
    ...UserFields
  }
}
mutation CreateUserWithCredentials(
  $password: passwords_insert_input!
  $user: users_insert_input!
) {
  insert_passwords_one(object: $password) {
    hash
  }
  insert_users_one(object: $user) {
    ...UserFields
  }
}
