query getUser($id: String!) {
  users(where: { id: { _eq: $id } }) {
    ...UserFields
  }
}

query getUserByEmail($email: String!) {
  users(where: { email: { _eq: $email } }) {
    ...UserFields
  }
}

query getMyUserByEmail($email: String!) {
  users(where: { email: { _eq: $email } }) {
    ...MyUserFields
  }
}

query getMyUserAndPasswordByEmail($email: String!) {
  users(where: { email: { _eq: $email } }) {
    ...MyUserFields
    passwords {
      ...PasswordFields
    }
  }
}

# mutation createUser($input: users_set_input!) {
#     insert_users_one(data: $input) {
#         ...UserFields
#     }
# }
