mutation DeleteAccount($id: String!) {
  delete_accounts_by_pk(id: $id) {
    id
  }
}

mutation LinkAccount($account: accounts_insert_input!) {
  insert_accounts_one(object: $account) {
    ...AccountFields
    userId
  }
}
