query getUser($id: String!) {
    users(where: { id: { _eq: $id } }) {
        ...UserFields
    }
}

query getMyUserByEmail($email: String!) {
    users(where: { email: { _eq: $email } }) {
        ...MyUserFields
    }
}

# mutation createUser($input: users_set_input!) {
#     insert_users_one(data: $input) {
#         ...UserFields
#     }
# }
