query getUsersAndAccountByEmail($email: String!) {
    users(where: { email: { _eq: $email } }) {
        ...UserFields
        accounts {
            ...AccountFields
        }
    }
}

mutation createUserWithCredentials(
    $user: users_insert_input!
    $password: passwords_insert_input!
) {
    insert_users_one(object: $user) {
        ...UserFields
    }
    insert_passwords_one(object: $password) {
        hash
    }
}
